processed_dataset_path_cl: ./datasets/processed_timit_dataset-conceptlayer
processed_dataset_path_tl: ./datasets/processed_timit_dataset-tasklayer
processed_dataset_path_joint: ./datasets/processed_timit_dataset-joint

load_processed_dataset: False   # If True, load processed TIMIT dataset with frames and labels from disk.

# Only used for task layer
framewise_labels: False
tl_input_representation: w2v2_features   # Options: binary_concepts (for independent optimization), concept_logits (for sequential optimization) or w2v2_features (as a test)

wav2vec2_feature_checkpoint: facebook/wav2vec2-base
wav2vec2_feature_batch_size: 4

model_checkpoint: facebook/wav2vec2-base    # Will be used for model and processor
concept_checkpoint_folder: /projects/0/prjs1921/thesis-speech/model_checkpoints/wav2vec2-conceptlayer
output_dir: /projects/0/prjs1921/thesis-speech/model_checkpoints/wav2vec2-tasklayer
output_dir_joint: /projects/0/prjs1921/thesis-speech/model_checkpoints/wav2vec2-joint

eval_strategy: steps
learning_rate: 0.001
per_device_train_batch_size: 32
per_device_eval_batch_size: 32
num_train_epochs: 20
logging_steps: 20
save_steps: 500
eval_steps: 500
warmup_steps: 1000
save_total_limit: 1
use_fp16: True
sample_validation_set: True
sample_validation_size: 0.10

joint_lambda: 0

use_initial_unfreeze: True      # If True, unfreeze specified wav2vec2 encoder layers from the start of training
unfreeze_layers: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]           # List of wav2vec2 encoder layer indices to unfreeze from the start of training (e.g., [8, 9, 10, 11] to unfreeze the last 4 layers)  

wandb_project: thesis-cbm       # WandB project name for logging training runs
run_name: wav2vec2-joint