#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=run_train
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --time=02:00:00
#SBATCH --output=outputs/run_train_%A.out

module purge
module load 2023
module load Anaconda3/2023.07-2

export HF_HOME="/projects/0/prjs1921/thesis-speech/.cache/huggingface"
export XDG_CACHE_HOME="/projects/0/prjs1921/thesis-speech/.cache"

source activate thesis-cbm
srun python train.py