#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --gpus=1
#SBATCH --job-name=run_train_baseline
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --time=01:00:00
#SBATCH --output=outputs/run_train_baseline_%A.out

mkdir -p "$TMPDIR/processed_datasets"
cp -r "/gpfs/home6/aeichholtz/msc-thesis/datasets/processed_timit_dataset-baselines" \
	"$TMPDIR/processed_datasets/processed_timit_dataset-baselines"

export PROCESSED_DATASET_PATH_BASELINES="$TMPDIR/processed_datasets/processed_timit_dataset-baselines"

export HF_HOME="$TMPDIR/hf_home"
export HF_DATASETS_CACHE="$TMPDIR/hf_datasets"
export TRANSFORMERS_CACHE="$TMPDIR/hf_models"

module purge
module load 2023
module load Anaconda3/2023.07-2

source activate thesis-cbm
python train_baseline.py